### ISSUE TITLE
[Suggestion]: Is there a way you can update a release version?

### ISSUE THREAD

**Issue by cyb3rgam3r** [ModernGamingWorld/Monumental-Experience#16]
### General Info

- [ ] I would like to suggest a new mod
- [ ] I would like to suggest a new quests
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

My server is unable to update the pack and i am still stuck on .83, i am not sure what it is involved but the .83 version says release instead of Beta, do you know when you will have another release version? I apologize if it seems i shouldnt be posting this, i am not sure why they are unable to update from curseforge, they said something about the server version but the one with the pack is updated so im not sure. but sorry i wasnt sure how to contact you about this other than here.
Thank you for your time.

**Comment by ModernGamingWorld** [comment]
The reason there haven't been any server files recently is due to some issues with certain mods, but those have now been resolved. Unfortunately, I haven’t had time to release the server files because of the busy holiday weekend. For quicker assistance, I recommend joining the Discord server and submitting a ticket. I, along with some of my Helpers, am more active there than on GitHub.

**Comment by ModernGamingWorld** [comment]
Waiting on CurseForge to approve the files
